services:
  php:
    build: ./docker/php-fpm/
    environment:
      PHP_IDE_CONFIG: "serverName=tc.local"
    volumes:
      - .:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 1.1.1.1      # Cloudflare
      - 8.8.8.8      # Google
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 5

  web:
    build: ./docker/apache/
    depends_on:
      php:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - ./docker/apache/vhosts.conf:/usr/local/apache2/conf/extra/vhost.conf
      - .:/var/www
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/server-status?auto"]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: mariadb:12.2
    environment:
      MYSQL_ROOT_PASSWORD: tc
      MYSQL_DATABASE: tc
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d/
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: tc
      UPLOAD_LIMIT: 300M
    depends_on:
      db:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8082:8025"
    volumes:
      - 'mailpit:/data'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://127.0.0.1:8025/ | grep -qi 'mailpit'" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db: ~
  mailpit: ~

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
