services:
  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=${SERVER_NAME:-tc.local}"
    volumes:
      - .:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 1.1.1.1      # Cloudflare
      - 8.8.8.8      # Google
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 5

  web:
      image: nginx:alpine
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
          - ./docker/nginx/certs:/etc/nginx/certs:ro
          - .:/var/www
      depends_on:
        php:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-fsS", "http://localhost/nginx-health"]
        interval: 30s
        timeout: 5s
        retries: 5

  db:
    image: mariadb:12.2
    environment:
      MYSQL_ROOT_PASSWORD: tc
      MYSQL_DATABASE: tc
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d/
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: tc
      UPLOAD_LIMIT: 300M
    depends_on:
      db:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8082:8025"
    volumes:
      - 'mailpit:/data'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://127.0.0.1:8025/ | grep -qi 'mailpit'" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  db: ~
  mailpit: ~
